#### HTTP GET
GET http://localhost:3001/api/persons

#### HTTP DELETE
DELETE http://localhost:3001/api/persons/2

#### HTTP POST
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
  "id": "",
  "name": "Dexter Morgan",
  "number": "050-3439"
}
#### HTTP POST (too short)
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "De",
  "number": "050-843793"
}